export const UNITS = {
  Liquid: ["ml", "l", "fl oz", "cup", "pint", "quart", "gallon", "tsp", "tbsp"],
  Weight: ["mg", "g", "kg", "oz", "lb"],
  Quantity: {
    Whole: [
      "piece",
      "item",
      "unit",
      "each",
      "whole",
      "half",
      "third",
      "quarter",
    ],
    Packs: ["pack", "package", "carton", "case", "dozen", "pair", "set"],
    Containers: ["bottle", "jar", "can", "bag", "box", "pouch", "tube", "tray"],
    Baking: [
      "loaf",
      "roll",
      "bun",
      "cake",
      "pie",
      "muffin",
      "slice",
      "sheet",
      "stick",
      "bar",
    ],
    Produce: ["bunch", "head", "stalk", "ear", "bundle", "sprig", "leaf", "clove"],
    Serving: [
      "serving",
      "portion",
      "helping",
      "scoop",
      "ladleful",
      "spoonful",
      "handful",
      "pinch",
      "dash",
      "drop",
      "drizzle",
      "splash",
      "squeeze",
    ],
  },
} as const;